#!/usr/bin/env bash

curl -LO https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
rm nvim-linux-x86_64.tar.gz

NVIM_EXPORT='export PATH="$PATH:/opt/nvim-linux-x86_64/bin"'
grep -qxF "$NVIM_EXPORT" ~/.bashrc || echo "$NVIM_EXPORT" >>~/.bashrc

sudo pacman -S cmake fd fzf lazygit ripgrep
sudo yay -S ttf-firacode-nerd

rm -rf ~/.config/nvim

rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.cache/nvim

git clone https://github.com/kennyek/lazyvim.nvim ~/.config/nvim
