unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key "C-f" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"

set -g mouse on
set -g allow-passthrough on
set -g base-index 1
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @modal-always-sticky on
set -g @modal-show-cmd-keys on
set -g @sessionist-alternate 'no-key'
set -g @sessionist-join-pane 'no-key'
set -g @sessionist-promote-window 'no-key'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'whame/tmux-modal'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'sainnhe/tmux-fzf'

run 'tpack init'
